=== backstage/backstage/packages/catalog-model/src/schema/Entity.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "Entity",
  "description": "The parts of the format that's common to all versions/kinds of entity.",
  "examples": [
    {
      "apiVersion": "backstage.io/v1alpha1",
      "kind": "Component",
      "metadata": {
        "name": "LoremService",
        "description": "Creates Lorems like a pro.",
        "labels": {
          "product_name": "Random value Generator"
        },
        "annotations": {
          "docs": "https://github.com/..../tree/develop/doc"
        }
      },
      "spec": {
        "type": "service",
        "lifecycle": "production",
        "owner": "tools"
      }
    }
  ],
  "type": "object",
  "required": ["apiVersion", "kind", "metadata"],
  "additionalProperties": false,
  "properties": {
    "apiVersion": {
      "type": "string",
      "description": "The version of specification format for this particular entity that this is written against.",
      "minLength": 1,
      "examples": ["backstage.io/v1alpha1", "my-company.net/v1", "1.0"]
    },
    "kind": {
      "type": "string",
      "description": "The high level entity type being described.",
      "minLength": 1,
      "examples": [
        "API",
        "Component",
        "Domain",
        "Group",
        "Location",
        "Resource",
        "System",
        "Template",
        "User"
      ]
    },
    "metadata": {
      "$ref": "EntityMeta"
    },
    "spec": {
      "type": "object",
      "description": "The specification data describing the entity itself."
    },
    "relations": {
      "type": "array",
      "description": "The relations that this entity has with other entities.",
      "items": {
        "$ref": "common#relation"
      }
    },
    "status": {
      "$ref": "common#status"
    }
  }
}

=== backstage/backstage/plugins/kubernetes-react/src/components/CustomResources/__fixtures__/analysis-run.json
{
  "apiVersion": "argoproj.io/v1alpha1",
  "kind": "AnalysisRun",
  "metadata": {
    "annotations": {
      "rollout.argoproj.io/revision": "4"
    },
    "creationTimestamp": "2021-03-09T15:05:49Z",
    "generation": 11,
    "labels": {
      "backstage.io/kubernetes-id": "dice-roller",
      "rollout-type": "Step",
      "rollouts-pod-template-hash": "546c476497",
      "step-index": "1"
    },
    "name": "dice-roller-546c476497-4-1",
    "namespace": "default",
    "ownerReferences": [
      {
        "apiVersion": "argoproj.io/v1alpha1",
        "blockOwnerDeletion": true,
        "controller": true,
        "kind": "Rollout",
        "name": "dice-roller",
        "uid": "8552f08d-32e8-4f95-a43f-8524763eef60"
      }
    ],
    "resourceVersion": "3342462005",
    "selfLink": "/apis/argoproj.io/v1alpha1/namespaces/default/analysisruns/dice-roller-546c476497-4-1",
    "uid": "b4e720ea-0488-42e2-8bd9-924c78843ee2"
  },
  "spec": {
    "metrics": [
      {
        "count": 5,
        "interval": "5s",
        "name": "always-pass",
        "provider": {
          "job": {
            "metadata": {
              "creationTimestamp": null
            },
            "spec": {
              "backoffLimit": 1,
              "template": {
                "metadata": {
                  "creationTimestamp": null
                },
                "spec": {
                  "containers": [
                    {
                      "image": "some-image",
                      "name": "always-pass",
                      "resources": {
                        "limits": {
                          "cpu": "800m",
                          "memory": "1G"
                        },
                        "requests": {
                          "cpu": "200m",
                          "memory": "1G"
                        }
                      }
                    }
                  ],
                  "restartPolicy": "Never"
                }
              }
            }
          }
        }
      }
    ]
  },
  "status": {
    "metricResults": [
      {
        "count": 5,
        "measurements": [
          {
            "finishedAt": "2021-03-09T15:06:13Z",
            "metadata": {
              "job-name": "b4e720ea-0488-42e2-8bd9-924c78843ee2.always-pass.1"
            },
            "phase": "Successful",
            "startedAt": "2021-03-09T15:05:49Z"
          },
          {
            "finishedAt": "2021-03-09T15:06:41Z",
            "metadata": {
              "job-name": "b4e720ea-0488-42e2-8bd9-924c78843ee2.always-pass.2"
            },
            "phase": "Successful",
            "startedAt": "2021-03-09T15:06:18Z"
          },
          {
            "finishedAt": "2021-03-09T15:07:08Z",
            "metadata": {
              "job-name": "b4e720ea-0488-42e2-8bd9-924c78843ee2.always-pass.3"
            },
            "phase": "Successful",
            "startedAt": "2021-03-09T15:06:46Z"
          },
          {
            "finishedAt": "2021-03-09T15:07:35Z",
            "metadata": {
              "job-name": "b4e720ea-0488-42e2-8bd9-924c78843ee2.always-pass.4"
            },
            "phase": "Successful",
            "startedAt": "2021-03-09T15:07:13Z"
          },
          {
            "finishedAt": "2021-03-09T15:08:02Z",
            "metadata": {
              "job-name": "b4e720ea-0488-42e2-8bd9-924c78843ee2.always-pass.5"
            },
            "phase": "Successful",
            "startedAt": "2021-03-09T15:07:40Z"
          }
        ],
        "name": "always-pass",
        "phase": "Successful",
        "successful": 5
      }
    ],
    "phase": "Successful",
    "startedAt": "2021-03-09T15:05:49Z"
  }
}

=== backstage/backstage/plugins/kubernetes-react/src/components/CustomResources/ArgoRollouts/__fixtures__/aborted-rollout.json
{
  "apiVersion": "argoproj.io/v1alpha1",
  "kind": "Rollout",
  "metadata": {
    "annotations": {
      "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"argoproj.io/v1alpha1\",\"kind\":\"Rollout\",\"metadata\":{\"annotations\":{},\"labels\":{\"backstage.io/kubernetes-id\":\"dice-roller\"},\"name\":\"dice-roller\",\"namespace\":\"default\"},\"spec\":{\"minReadySeconds\":30,\"replicas\":4,\"selector\":{\"matchLabels\":{\"app\":\"dice-roller\",\"backstage.io/kubernetes-id\":\"dice-roller\"}},\"strategy\":{\"canary\":{\"maxSurge\":\"25%\",\"maxUnavailable\":0,\"steps\":[{\"setWeight\":10},{\"analysis\":{\"templates\":[{\"templateName\":\"always-pass\"}]}},{\"pause\":{\"duration\":\"1m\"}},{\"setWeight\":20},{\"pause\":{\"duration\":\"1m\"}},{\"analysis\":{\"templates\":[{\"templateName\":\"always-pass\"}]}}]}},\"template\":{\"metadata\":{\"labels\":{\"app\":\"dice-roller\",\"backstage.io/kubernetes-id\":\"dice-roller\",\"start\":\"1234\"}},\"spec\":{\"containers\":[{\"image\":\"nginx:1.15.4\",\"name\":\"nginx\",\"ports\":[{\"containerPort\":80}]}]}}}}\n",
      "rollout.argoproj.io/revision": "4"
    },
    "creationTimestamp": "2021-03-08T10:38:23Z",
    "generation": 12,
    "labels": {
      "backstage.io/kubernetes-id": "dice-roller"
    },
    "name": "dice-roller",
    "namespace": "default",
    "resourceVersion": "3336911046",
    "selfLink": "/apis/argoproj.io/v1alpha1/namespaces/default/rollouts/dice-roller",
    "uid": "8552f08d-32e8-4f95-a43f-8524763eeg60"
  },
  "spec": {
    "minReadySeconds": 30,
    "replicas": 4,
    "selector": {
      "matchLabels": {
        "app": "dice-roller",
        "backstage.io/kubernetes-id": "dice-roller"
      }
    },
    "strategy": {
      "canary": {
        "maxSurge": "25%",
        "maxUnavailable": 0,
        "steps": [
          {
            "setWeight": 10
          },
          {
            "analysis": {
              "templates": [
                {
                  "templateName": "always-pass"
                }
              ]
            }
          },
          {
            "pause": {
              "duration": "1h"
            }
          },
          {
            "setWeight": 20
          },
          {
            "pause": {
              "duration": "1m"
            }
          },
          {
            "analysis": {
              "templates": [
                {
                  "templateName": "always-pass"
                }
              ]
            }
          }
        ]
      }
    },
    "template": {
      "metadata": {
        "creationTimestamp": null,
        "labels": {
          "app": "dice-roller",
          "backstage.io/kubernetes-id": "dice-roller",
          "start": "1236"
        }
      },
      "spec": {
        "containers": [
          {
            "image": "nginx:1.15.4",
            "name": "nginx",
            "ports": [
              {
                "containerPort": 80
              }
            ],
            "resources": {}
          }
        ]
      }
    }
  },
  "status": {
    "HPAReplicas": 4,
    "availableReplicas": 4,
    "blueGreen": {},
    "canary": {},
    "conditions": [
      {
        "lastTransitionTime": "2021-03-08T10:39:31Z",
        "lastUpdateTime": "2021-03-08T10:39:31Z",
        "message": "Rollout has minimum availability",
        "reason": "AvailableReason",
        "status": "True",
        "type": "Available"
      },
      {
        "lastTransitionTime": "2021-03-09T16:11:14Z",
        "lastUpdateTime": "2021-03-09T16:13:09Z",
        "message": "some metric related failure message",
        "reason": "RolloutAborted",
        "status": "False",
        "type": "Progressing"
      }
    ],
    "currentPodHash": "546c476497",
    "currentStepHash": "5b48bb87dc",
    "currentStepIndex": 0,
    "observedGeneration": "12",
    "readyReplicas": 4,
    "replicas": 4,
    "selector": "app=dice-roller,backstage.io/kubernetes-id=dice-roller",
    "stableRS": "546c476497",
    "updatedReplicas": 4
  }
}

=== backstage/backstage/plugins/kubernetes-react/src/components/HorizontalPodAutoscalers/__fixtures__/horizontalpodautoscalers.json
[
  {
    "apiVersion": "autoscaling/v2",
    "kind": "HorizontalPodAutoscaler",
    "metadata": {
      "annotations": {},
      "creationTimestamp": "2024-02-13T20:13:52Z",
      "labels": {
        "backstage.io/kubernetes-id": "dice-roller"
      },
      "name": "dice-roller",
      "namespace": "default",
      "resourceVersion": "6717s736",
      "uid": "a34c90e1-8e8f-407f-b4c5-b4543bd56c1b"
    },
    "spec": {
      "maxReplicas": 15,
      "metrics": [
        {
          "resource": {
            "name": "cpu",
            "target": {
              "averageUtilization": 30,
              "type": "Utilization"
            }
          },
          "type": "Resource"
        }
      ],
      "minReplicas": 10,
      "scaleTargetRef": {
        "apiVersion": "apps/v1",
        "kind": "Deployment",
        "name": "dice-roller"
      }
    },
    "status": {
      "conditions": [
        {
          "lastTransitionTime": "2024-05-17T19:50:35Z",
          "message": "recent recommendations were higher than current one, applying the highest recent recommendation",
          "reason": "ScaleDownStabilized",
          "status": "True",
          "type": "AbleToScale"
        },
        {
          "lastTransitionTime": "2024-05-16T06:21:01Z",
          "message": "the HPA was able to successfully calculate a replica count from cpu resource utilization (percentage of request)",
          "reason": "ValidMetricFound",
          "status": "True",
          "type": "ScalingActive"
        },
        {
          "lastTransitionTime": "2024-05-16T06:21:01Z",
          "message": "the desired replica count is more than the maximum replica count",
          "reason": "TooManyReplicas",
          "status": "True",
          "type": "ScalingLimited"
        }
      ],
      "currentMetrics": [
        {
          "resource": {
            "current": {
              "averageUtilization": 50,
              "averageValue": "50m",
              "value": "100m"
            },
            "name": "cpu"
          },
          "type": "Resource"
        }
      ],
      "currentReplicas": 13,
      "desiredReplicas": 14,
      "lastScaleTime": "2024-02-13T20:14:23Z"
    }
  }
]
